### ISSUE TITLE
Animal logo missing?

### ISSUE THREAD

**Issue by valstu** [turansadri/linnut-redux#1]
Seems like this project is missing animal logo?

**Comment by petetnt** [comment]
We would like to use this library at our company, but we have strict policy of using only libraries that have animal logos, so it's a no-go from our legal dept. If you could add an animal logo it would be much easier to get this into production.

**Comment by sirtawast** [comment]
Some logos that you might consider and are natively supported by most of things: 🐦  🐉  🐍  🐌  🐳  🐬  🦄  🐥 

Though one with a bird might be more appropriate.
